### ISSUE TITLE
README.md: Installation issue report

### ISSUE THREAD

**Issue by wangcc0218** [s4hts/MultiQC#6]
### Description of feature

Hi Bradly,

According to the installation instruction in README.md, it seems "If you would like the development version instead, the command is: pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git". 

However, actually with this command, I can only get the original version of MultiQC, but not the version working with HTStream JSON files. I think the correct command should be: pip install --upgrade --force-reinstall git+https://github.com/s4hts/MultiQC.git

Thanks, 
Congcong

**Comment by bnjenner** [comment]
Hello Congcong,

This is true. Since this is a development version of MultiQC concerned with developing support for HTStream, the documentation has not been updated. 

Hope you are finding the module useful!

Best,
Bradley

**Comment by bnjenner** [comment]
Documentation Not Updated
